apiVersion: v1
kind: Secret
type: Opaque
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "dataspace-connector.fullname" . }}
  labels:
    {{- include "dataspace-connector.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.env.secrets }}
  {{ $key }}: "{{ $val | b64enc }}"
{{- end}}
{{- if .Values.postgresql }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgresql.auth.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgresql.auth.password | b64enc }}
{{- end}}
